"""posts table

Revision ID: 952202e29a6d
Revises: 4bee5568567e
Create Date: 2020-05-25 08:43:05.758449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952202e29a6d'
down_revision = '4bee5568567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'price')
    # ### end Alembic commands ###
